name: CI

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install deps
        run: sudo apt-get update && sudo apt-get install -y build-essential
      
      - name: Build
        run: make

      - name: Run tests
        run: |
          if make -n test >/dev/numm 2>&1; then
            make test
          else
            echo "No test target"
          fi